default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


sensor:
  - platform: mqtt
    state_topic: "/home/esp32/ethernet_kit"
    name: 'BLE RSSI'
    unit_of_measurement: 'dbm'
    value_template: '{{ value_json.rssi }}'
    device_class: humidity